image: node

stages:
  - build
  - test

compile:
  stage: build
  script:
    - echo "BUILD"
    - npm ci
    - npm run build

test:
  stage: test
  script:
    - echo "TEST"
    - npm ci
    - npm run test:unit
  coverage: /All\sfiles.*?\s+(\d+.\d+)/